// Club Normalization Dictionary
export const CLUB_ALIAS_MAP: Record<string, string> = {
  'psg': 'Paris Saint-Germain',
  'paris sg': 'Paris Saint-Germain',
  'paris saint germain': 'Paris Saint-Germain',
  'man city': 'Manchester City',
  'manchester city fc': 'Manchester City',
  'mcfc': 'Manchester City',
  'man utd': 'Manchester United',
  'man united': 'Manchester United',
  'manchester united fc': 'Manchester United',
  'mufc': 'Manchester United',
  'united': 'Manchester United',
  'barca': 'Barcelona',
  'fc barcelona': 'Barcelona',
  'real': 'Real Madrid',
  'real madrid cf': 'Real Madrid',
  'juve': 'Juventus',
  'juventus fc': 'Juventus',
  'inter': 'Inter Milan',
  'internazionale': 'Inter Milan',
  'inter milan': 'Inter Milan',
  'ac milan': 'AC Milan',
  'milan': 'AC Milan',
  'bayern': 'Bayern Munich',
  'fc bayern': 'Bayern Munich',
  'bvb': 'Borussia Dortmund',
  'dortmund': 'Borussia Dortmund',
  'spurs': 'Tottenham Hotspur',
  'tottenham': 'Tottenham Hotspur',
  'arsenal fc': 'Arsenal',
  'chelsea fc': 'Chelsea',
  'liverpool fc': 'Liverpool',
  'atletico': 'Atlético Madrid',
  'atletico madrid': 'Atlético Madrid',
  'roma': 'AS Roma',
  'napoli': 'Napoli',
  'ssc napoli': 'Napoli',
  'om': 'Marseille',
  'olympique marseille': 'Marseille',
  'olympique de marseille': 'Marseille',
  'lyon': 'Lyon',
  'olympique lyonnais': 'Lyon',
  'leverkusen': 'Bayer Leverkusen',
  'bayer 04': 'Bayer Leverkusen',
  'ajax': 'Ajax',
  'afc ajax': 'Ajax',
  'villa': 'Aston Villa',
  'newcastle': 'Newcastle United',
  'nufc': 'Newcastle United',
  'everton fc': 'Everton',
  'westham': 'West Ham United',
  'west ham': 'West Ham United',
  'sporting': 'Sporting CP',
  'sporting lisbon': 'Sporting CP',
  'porto': 'FC Porto',
  'benfica': 'SL Benfica',
};

export function normalizeClubName(rawName: string): string {
  const clean = rawName.trim().toLowerCase();
  if (CLUB_ALIAS_MAP[clean]) {
    return CLUB_ALIAS_MAP[clean];
  }
  return rawName.trim();
}
